import './globals.css'
import NavMenu from '@/components/NavMenu'
import { Inter } from 'next/font/google'
import AuthProvider from './AuthProvider'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (

      <html lang="en">
        <body className={inter.className}>
          <AuthProvider>
            <NavMenu />
            <main className='container py-6 text-black'>
              {children}
            </main>
          </AuthProvider>
        </body>
      </html>
    
  )
}
